name: Process Video to HLS

on:
  push:
    branches:
      - main

jobs:
  Download-and-Process:
    runs-on: ubuntu-latest
    permissions:
       contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Extract Video URL and ID
      id: extract_url
      run: |
        VIDEO_URL=$(cat link.txt)
        echo "Video URL is $VIDEO_URL"
        echo "VIDEO_URL=$VIDEO_URL" >> $GITHUB_ENV
      # Replace "path/to/url_file.txt" with the path to the file containing the video URL.

    - name: Install FFMPEG and Git
      run: sudo apt-get update && sudo apt-get install -y ffmpeg git

    - name: Download Video
      run: wget -O video ${{ env.VIDEO_URL }}
      # Uses the extracted URL to download the video.

    - name: Make Output Folder
      run: |
        mkdir hls_output
        mkdir hls_output/240p
        mkdir hls_output/360p
        mkdir hls_output/480p
        mkdir hls_output/720p
        mkdir hls_output/1080p
        ls

    - name: Convert Video to HLS using FFmpeg
      run: |
        ffmpeg -i video -vf "scale=-1:240" -codec:v libx264 -codec:a aac -b:v 800k -hls_time 12 -hls_playlist_type vod -start_number 0 -hls_list_size 0 -f hls ./hls_output/240p/index.m3u8 &
        ffmpeg -i video -vf "scale=-1:360" -codec:v libx264 -codec:a aac -b:v 1400k -hls_time 12 -hls_playlist_type vod -start_number 0 -hls_list_size 0 -f hls ./hls_output/360p/index.m3u8 &
        ffmpeg -i video -vf "scale=-1:480" -codec:v libx264 -codec:a aac -b:v 2000k -hls_time 12 -hls_playlist_type vod -start_number 0 -hls_list_size 0 -f hls ./hls_output/480p/index.m3u8 &
        ffmpeg -i video -vf "scale=-1:720" -codec:v libx264 -codec:a aac -b:v 3500k -hls_time 12 -hls_playlist_type vod -start_number 0 -hls_list_size 0 -f hls ./hls_output/720p/index.m3u8 &
        ffmpeg -i video -vf "scale=-1:1080" -codec:v libx264 -codec:a aac -b:v 6000k -hls_time 12 -hls_playlist_type vod -start_number 0 -hls_list_size 0 -f hls ./hls_output/1080p/index.m3u8 &
        wait
      # This will create an HLS playlist (index.m3u8) and the .ts files in the "hls_output" directory.
      
    - name: Copy HLS Files
      run: |
        mkdir hls-content
        ls
        cp -r hls_output/* hls-content
        cp master.m3u8 hls-content
      # This copies all HLS files into the target repository's directory.

    - name: Commit and Push HLS Files
      run: |
        VIDEO_ID=$(cat name.txt)
        echo "Video Id is $VIDEO_ID"
        
        cd hls-content
        ls
        git init
        git config --global user.name 'hindu744'
        git config --global user.email 'hhindu744@gmail.com'
        # git config --global init.defaultBranch ${{ env.VIDEO_ID }}
        git branch -m testv5
        git add .
        git commit -m "Upload HLS files"
        git remote add origin https://github.com/hindu744/hls-content.git
        git remote set-url origin https://hindu744:${{secrets.TOKEN}}@github.com/hindu744/hls-content
        git push --set-upstream origin testv5
        git push origin testv5
