name: Process Video to HLS

on:
  push:
    branches:
      - main
jobs:
  Download-and-Process:
    runs-on: ubuntu-latest
    permissions:
       contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install FFMPEG and Git
      run: sudo apt-get update && sudo apt-get install -y ffmpeg git tree axel

    - name: Download Video
      run: wget -O video "$(cat link.txt)"

    - name: Make Output Folder
      run: mkdir hls_output hls_output/240p hls_output/360p hls_output/480p hls_output/720p hls_output/1080p

    - name: Convert Video to HLS using FFMPEG
      run: ffmpeg -i video -filter_complex 
          "[0:v]split=5[v240][v360][v480][v720][v1080]; 
          [v240]scale=-2:240[v240out]; 
          [v360]scale=-2:360[v360out]; 
          [v480]scale=-2:480[v480out]; 
          [v720]scale=-2:720[v720out]; 
          [v1080]scale=-2:1080[v1080out]" 
          -map "[v240out]" -map 0:a -codec:v libx264 -codec:a aac -b:v 800k -hls_time 12 -hls_flags independent_segments -hls_segment_type mpegts -hls_playlist_type vod -start_number 0 -hls_list_size 0 -f hls ./hls_output/240p/index.m3u8 
          -map "[v360out]" -map 0:a -codec:v libx264 -codec:a aac -b:v 1400k -hls_time 12 -hls_flags independent_segments -hls_segment_type mpegts -hls_playlist_type vod -start_number 0 -hls_list_size 0 -f hls ./hls_output/360p/index.m3u8 
          -map "[v480out]" -map 0:a -codec:v libx264 -codec:a aac -b:v 2000k -hls_time 12 -hls_flags independent_segments -hls_segment_type mpegts -hls_playlist_type vod -start_number 0 -hls_list_size 0 -f hls ./hls_output/480p/index.m3u8 
          -map "[v720out]" -map 0:a -codec:v libx264 -codec:a aac -b:v 3500k -hls_time 12 -hls_flags independent_segments -hls_segment_type mpegts -hls_playlist_type vod -start_number 0 -hls_list_size 0 -f hls ./hls_output/720p/index.m3u8 
          -map "[v1080out]" -map 0:a -codec:v libx264 -codec:a aac -b:v 6000k -hls_time 12 -hls_flags independent_segments -hls_segment_type mpegts -hls_playlist_type vod -start_number 0 -hls_list_size 0 -f hls ./hls_output/1080p/index.m3u8

    - name: Copy HLS Files
      run: |
        mkdir hls-content
        tree
        cp -r hls_output/* hls-content
        cp master.m3u8 hls-content
        cp name.txt hls-content

    - name: Commit and Push HLS Files
      run: |
        cd hls-content
        git init
        git config --global user.name 'hindu744'
        git config --global user.email 'hhindu744@gmail.com'

        BRANCH_NAME=$(cat name.txt | tr -d '[:space:]')
        git branch -m "$BRANCH_NAME"
        git add .
        git commit -m "Upload HLS files $BRANCH_NAME"
        git remote add origin https://github.com/hindu744/hls-content.git
        git remote set-url origin https://hindu744:${{secrets.TOKEN}}@github.com/hindu744/hls-content.git
        # git push --set-upstream origin $(cat name.txt)
        git push origin "$BRANCH_NAME"
